<?php



namespace VW\ClientBundle\Repository;



use Doctrine\ORM\EntityRepository;



/**

 * CategorieRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class CategorieRepository extends \Doctrine\ORM\EntityRepository

{

    

    function findAll(){

            

                return $this->findBy(array(), array('nom' => 'ASC'));

        }

    



    

    public function getLikeQueryBuilder($pattern)

  {

    return $this

      ->createQueryBuilder('c')

      ->where('c.nom LIKE :pattern')

      ->setParameter('pattern', $pattern)

    ;

  }

    

    

}

