<?php



namespace VW\ClientBundle\Repository;



use Doctrine\ORM\EntityRepository;



/**

 * VilleRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class VilleRepository extends \Doctrine\ORM\EntityRepository

{

    function findAll(){

            

                return $this->findBy(array(), array('nom' => 'ASC'));

        }

    

    

    public function getLikeQueryBuilder($pattern)

      {

        return $this

          ->createQueryBuilder('v')

          ->where('v.nom LIKE :pattern')

          ->orderBy("v.nom", 'ASC')

          ->setParameter('pattern', $pattern)

        ;

      }

}

