imports:
  - { resource: config.yml }

doctrine:
  dbal:
    driver: pdo_mysql
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: utf8mb4
    server_version: "8.0"
    # options:
    #   2: 5            # PDO::ATTR_TIMEOUT => 5 (optionnel)
    #   1009: "/app/certs/ca.pem"  # PDO::MYSQL_ATTR_SSL_CA (si TLS avec CA)
    #   1013: false                # PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT

monolog:
  handlers:
    main:
      type: stream
      path: "php://stderr"
      level: error
      channels: ["!event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!doctrine"]

framework:
  session:
    handler_id: ~
    save_path: "/tmp/sessions"
