payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
    options: { i18n: false }

vw_abonnement:
    resource: "@VWAbonnementBundle/Resources/config/routing.yml"
    prefix:   /

vw_client:
    resource: "@VWClientBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /password

vw_seo:
    resource: "@VWSeoBundle/Resources/config/routing.yml"
    prefix:   /

vw_contact:
    resource: "@VWContactBundle/Resources/config/routing.yml"
    prefix:   /

vw_base:
    resource: "@VWBaseBundle/Resources/config/routing.yml"
    prefix:   /
