<?php



namespace VW\BaseBundle\Repository;



/**

 * PagesRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class PagesRepository extends \Doctrine\ORM\EntityRepository

{

    

    public function myFindAll()

  {

    



    return $this

    ->createQueryBuilder('a')

    ->getQuery()

    ->getResult()

  ;

  }

}

