<?php



namespace VW\AbonnementBundle\Repository;



/**

 * CategorieRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class CategorieRepository extends \Doctrine\ORM\EntityRepository

{

    

    function findAll(){

            

                return $this->findBy(array(), array('nom' => 'ASC'));

        }

}

