<?php



namespace VW\AbonnementBundle\Repository;



/**

 * ConditionRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class ConditionRepository extends \Doctrine\ORM\EntityRepository

{

}

