<?php



namespace VW\AbonnementBundle\Repository;



/**

 * ImageConjointRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class ImageConjointRepository extends \Doctrine\ORM\EntityRepository

{

}

