<?php



namespace VW\AbonnementBundle\Repository;



/**

 * LocationFatbikeRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class LocationFatbikeRepository extends \Doctrine\ORM\EntityRepository

{

}

