<?php



namespace VW\AbonnementBundle\Repository;



/**

 * LocationTraineauRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class LocationTraineauRepository extends \Doctrine\ORM\EntityRepository

{

}

