<?php



namespace VW\AbonnementBundle\Repository;



/**

 * LocationSkiRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class LocationSkiRepository extends \Doctrine\ORM\EntityRepository

{

}

