<?php



namespace VW\AbonnementBundle\Repository;



/**

 * LocationRaquetteRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class LocationRaquetteRepository extends \Doctrine\ORM\EntityRepository

{

}

