<?php



namespace VW\AbonnementBundle\Repository;



/**

 * PasseRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class PasseRepository extends \Doctrine\ORM\EntityRepository

{

    

      public function getLikeQueryBuilder($pattern)

          {

            return $this

              ->createQueryBuilder('p')

              ->where('p.id LIKE :pattern')

              ->setParameter('pattern', $pattern)

            ;

          }

}

