<?php



namespace VW\AbonnementBundle\Repository;



/**

 * SentierRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class SentierRepository extends \Doctrine\ORM\EntityRepository

{

}

