<?php



namespace VW\AbonnementBundle\Repository;



/**

 * TypeAbonnementRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class TypeAbonnementRepository extends \Doctrine\ORM\EntityRepository

{

    

    function findAll(){

            

                return $this->findBy(array(), array('id' => 'ASC'));

        }

}

