vw_contact:
  path: /{_locale}/contact
  defaults:
    _controller: 'VWContactBundle:Default:add'
    _locale: fr
  requirements:
    _locale: fr|en
  methods: [GET, POST]

vw_contact_model:
    path:     /contact/model
    defaults: { _controller: VWContactBundle:Default:model }

vw_contact_form:
    path:     /form/{name}
    defaults: { _controller: VWContactBundle:Default:index }


vw_contact_envoye:
    path:     /contact/{id}
    defaults:
        _controller: VWContactBundle:Default:envoye
    requirements:
        id: \d+

vw_contact_journal:
    path:     contact/journal
    defaults: { _controller: VWContactBundle:Default:journal }

